### ISSUE TITLE
wait-on keeps polling even after a web server has been found.

### ISSUE THREAD

**Issue by Pomax** [jeffbski/wait-on#34]
**edit** note that if you find this issue because you've run into the same problem with v3.2.0, there is a [`3.3.0-beta.0` branch](https://github.com/jeffbski/wait-on/issues/34#issuecomment-458130475) that you should try, to see if that fixes it. If it does, please report back. If it does not, please _also_ report back.

---

I'm using `wait-on http://localhost:8000 && test:server` (v3.2.0) in a run script and was seeing my server go absolutely nuts trying to serve up the `/` route every 250ms after starting up:

```
System check identified no issues (0 silenced).
January 17, 2019 - 11:10:07
Django version 1.11.18, using settings 'networkapi.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[17/Jan/2019 11:10:07] "HEAD / HTTP/1.1" 302 0
[17/Jan/2019 11:10:07] "HEAD /en/ HTTP/1.1" 200 17877
[17/Jan/2019 11:10:07] "HEAD / HTTP/1.1" 302 0
[17/Jan/2019 11:10:07] "HEAD /en/ HTTP/1.1" 200 17877
[17/Jan/2019 11:10:07] "HEAD / HTTP/1.1" 302 0
[17/Jan/2019 11:10:07] "HEAD /en/ HTTP/1.1" 200 17877
[17/Jan/2019 11:10:07] "HEAD / HTTP/1.1" 302 0
[17/Jan/2019 11:10:07] "HEAD /en/ HTTP/1.1" 200 17877
[...snip...]
```

I thought the redirect was the problem here, but directly pointing to `/en/` still does the same thing:

```
System check identified no issues (0 silenced).
January 17, 2019 - 11:14:56
Django version 1.11.18, using settings 'networkapi.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[17/Jan/2019 11:14:57] "HEAD /en/ HTTP/1.1" 200 17877
[17/Jan/2019 11:14:57] "HEAD /en/ HTTP/1.1" 200 17877
[17/Jan/2019 11:14:57] "HEAD /en/ HTTP/1.1" 200 17877
[17/Jan/2019 11:14:57] "HEAD /en/ HTTP/1.1" 200 17877
[...snip...]
```

how do I tell wait-for to not interfere once it's found what it has been told to look out for? I tried using `-w 500` and `--window 500` but neither of those do anything. wait-for just keeps polling.

**Comment by jeffbski** [comment]
The flow works as follows it starts with any delay that is set (default 0) then it checks the services and repeats at the interval time (default 250ms) and after the stabilization window time (default 750ms) has passed if it is still succeeding then it considers it a success and exits, allowing your test to start running. 

One main reason to have the stabilization window is if one is waiting on files that are being built, it will check the size and see that it isn't continuing to be written to before it considers it ready. It is less important for http checks but one mechanism governs all the checks. 

So if you simply want to wait for an http server to start and are not waiting for any files to be built, then you can simply set the window to the same as the interval time and you'll typically see just two checks and it will exit. Once it exits allowing your next program to run, it does not do any further checks.

```bash
wait-on -i 250 -w 250 http://localhost:8000/en && testxyx  # this does a HEAD check looking for 200 status code
# OR you could do a HTTP GET check
wait-on -i 250 -w 250 http-get://localhost:8000/en && testxyx  # this does a GET check looking for 200 status code
```

If you add the -v option you will also see some extra debug logging.

**Comment by Pomax** [comment]
But as mentioned: `-w` does _not_ make it stop polling. The server comes on, the "command to run once things are stable" gets triggered, but `wait-on` _keeps polling as well_

**Comment by jeffbski** [comment]
If your command line is correct then the only way for it to run your next command is for wait-on to exit with an exit code of 0 or 1. It cannot continue to poll after it has exited. 

So the only way it can continue to poll is to not have exited (and thus your next command would not have been run yet. )

If both are running then maybe you used a single & (running it as a background job so it wouldn't wait) and not a && which will wait for wait-on to exit successfully.

In either case if it is continuing to poll then it has not succeeded (and exited) so run it with -v to help see what is going on. Try running it just by itself with -v and see if it exits. You can post the output of that here and I can try to help you debug. 

Note that you use http:// for it to do a HEAD 200 check or http-get:// to do a GET 200 check. Not all servers have implemented HEAD so you can use the GET check if necessary. From your logs it looked like both would work.

**Comment by jeffbski** [comment]
You could also make sure that you don't have a process already running in the background that is hitting the server. Start up your django server by itself and make sure nothing is hitting it. Maybe an earlier run with a single & is still running??

**Comment by Pomax** [comment]
I think I know what's going on. It looks like wait-on is buffering its request, so if I run a server first, then run wait-on, it tries four times, and we're done.

However, reverse those and requests start to pile up: run wait-on and immediately start server = 4~8 requests, Start wait-on and have the server start a few seconds later: quite a few more requests. Start wait-on and the server starts 10+ seconds later (e.g. due to an asset build in between): an insane number of requests =)

So it looks like wait-on is building up a backbuffer while waiting, which shouldn't be necessary.

**Comment by jeffbski** [comment]
You could use the delay option -d to have it wait N milliseconds before it starts polling and that should reduce the number of tries.

**Comment by jeffbski** [comment]
yes, you would run whatever necessary to start the django server first then run the wait-on check before launching whatever comes next.

**Comment by jeffbski** [comment]
It looks like that setting currently only applies to the low level tcp connections, but you are right, we should have a timeout setting available for HTTP HEAD and GET requests. 

I think it is probably fine to apply the same setting (tcpTimeout) for HTTP HEAD and GET requests too. Seems like that should be acceptable. I think if it isn't set then it uses the underlying OS's defaults which are probably pretty high. 

I can make the change and put out a beta version for you to try it.

**Comment by jeffbski** [comment]
In thinking about it, I think the safest thing for me to do is to just create a separate httpTimeout setting separate from tcpTimeout that way it wouldn't affect any other uses. Plus one might need a longer httpTimeout than tcpTimeout since it would include retrieving a response.

**Comment by Pomax** [comment]
I'd be happy to help test. It might also make sense to have a way to say "timeouts are not actually an error", since firing up a server is plain old going to succeed, with the error coming from the GET/HEAD response (2xx/3xx? success! 4xx/5xx? boo!). That way no requests "pile up", so you won't get multiple requests when the server comes up just because `wait-on` was running for a few seconds before the server came online.

**Comment by jeffbski** [comment]
I have pushed up a beta of this feature for you to try out. 

Let me know if you think we need to add anything else to the wording (Readme, help)

You would try this out by using 
npm i wait-on@next

**Comment by Pomax** [comment]
cheers, I'll give that a shot today and report back!

**Comment by Pomax** [comment]
Hmm, so I'm still seeing it do the following, using 3.3.0-beta.0:
```
> network@1.0.0 cypress:test C:\Users\Pomax\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> wait-on http://localhost:8000/en/ -i 500 -w 500 --httpTimeout 500 && cypress run

Loading .env environment variables…
Performing system checks...

System check identified no issues (0 silenced).
January 29, 2019 - 17:00:02
Django version 1.11.18, using settings 'networkapi.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2019-01-29 17:00:03,135 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:03,135 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:03,571 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:03,571 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:04,074 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:04,074 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:04,571 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:04,571 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:05,070 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:05,070 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:05,573 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:05,573 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:06,071 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:06,071 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:06,573 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
2019-01-29 17:00:06,573 [INFO] "HEAD /en/ HTTP/1.1" 200 18059
```

**Comment by jeffbski** [comment]
It looks like it is taking 3-4 seconds to start so you could add a delay to your command "-d 3000" to make it start checking after 3 seconds.

**Comment by Pomax** [comment]
I forgot to indicate that was snipped: just like 3.2.0 wait-on keeps polling forever, despite the server sending HEAD:200 ever 250ms when asked by wait-for. This is on Windows 10, but given that the server's clearly getting asked for a HEAD response, and it sends one, I wouldn't imagine that to actually be relevant in this case.

(I'm waiting on tcp:8000 in the mean time, which certainly lets us get on with the job of testing, so we're not "blocked" by this, but it'd certainly be better to be able to check that a specific route is up =)

**Comment by Pomax** [comment]
I'm using `cmd`, and Visual Studio Code's built in shell, which is also `cmd`, so... no powershell here.

It might be worth going down the same route that `forever` etc. use, with a flag that lets you quote the task  that needs to run instead of relying on shell syntax. E.g. `wait-on http://localhost:8000/en/api/v1/test -m "npm run cypress"`?

**Comment by jeffbski** [comment]
Didn't necessarily want to go that route since then I'd be starting up a new process and all. Wanted this to be very simple and get out of the way as soon as things were up. 

So now I am really still confused. I don't know how your "npm run cypress" can be running at all if you wait-on is still polling. I will be interested in the "-v" output.

**Comment by Pomax** [comment]
fair enough. and that's the whole problem: _it's not_, wait-on keeps polling, and polling, and polling, clearly never actually going "oh wait I'm getting responses, I should move on".

**Comment by jeffbski** [comment]
ok, I had misunderstood. I thought it was running the next thing and also still polling which should literally be impossible (can't return an exit code and keep running).

So now we just need to figure out why it isn't considering the response a successful match.

**Comment by Pomax** [comment]
`-v` output:

```
> network@1.0.0 cypress C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> run-p --race server cypress:test


> network@1.0.0 server C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> pipenv run python network-api/manage.py runserver


> network@1.0.0 cypress:test C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> wait-on -v http://localhost:8000/en && cypress run

Loading .env environment variables…
child next []
child complete
child next [ { 'http://localhost:8000/en': -999 } ]
child complete
child next []
child complete
Performing system checks...

System check identified no issues (0 silenced).
child next []
child complete

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): news.
Run 'python manage.py migrate' to apply them.
February 05, 2019 - 08:49:37
Django version 1.11.18, using settings 'networkapi.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2019-02-05 08:49:38,128 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,128 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,235 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,235 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,240 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,240 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,318 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,318 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,322 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,322 [INFO] "HEAD /en HTTP/1.1" 301 0
child next []
child complete
2019-02-05 08:49:38,401 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,401 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,405 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,405 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,481 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,481 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,484 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,484 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,562 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,562 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,565 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,565 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,641 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,641 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,644 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,644 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,720 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,720 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,723 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,723 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,798 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,798 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,801 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,801 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,875 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,875 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,878 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,878 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,953 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,953 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:38,956 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:38,956 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,032 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,032 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,035 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,035 [INFO] "HEAD /en HTTP/1.1" 301 0
child next [ { 'http://localhost:8000/en': 200 },
  { 'http://localhost:8000/en': -999 },
  { 'http://localhost:8000/en': 200 },
  { 'http://localhost:8000/en': -999 } ]
child complete
2019-02-05 08:49:39,115 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,115 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,118 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,118 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,196 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,196 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,199 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,199 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,279 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,279 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,282 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,282 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,357 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,357 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,361 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,361 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,438 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,438 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,441 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,441 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,516 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,516 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,594 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,594 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,672 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,672 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,844 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:39,844 [INFO] "HEAD /en HTTP/1.1" 301 0
child next []
child complete
2019-02-05 08:49:39,919 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:39,919 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,094 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,094 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,172 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,172 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,345 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,345 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,424 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,424 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,594 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,594 [INFO] "HEAD /en HTTP/1.1" 301 0
child next []
child complete
2019-02-05 08:49:40,671 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,671 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,843 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,843 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:40,918 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:40,918 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,094 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,094 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,173 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,173 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,345 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,345 [INFO] "HEAD /en HTTP/1.1" 301 0
child next []
child complete
2019-02-05 08:49:41,421 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,421 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,594 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,594 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,674 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,674 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,845 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,845 [INFO] "HEAD /en HTTP/1.1" 301 0
2019-02-05 08:49:41,923 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
2019-02-05 08:49:41,923 [INFO] "HEAD /en/ HTTP/1.1" 200 17905
[...snip...]
```

**Comment by jeffbski** [comment]
how about using http-get://   with -v ?

I'd be curious to see that as well.

**Comment by Pomax** [comment]
definitely better, but also crashy =)
```
> network@1.0.0 cypress C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> run-p --race server cypress:test


> network@1.0.0 cypress:test C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> wait-on -v http-get://localhost:8000/en && cypress run


> network@1.0.0 server C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org
> pipenv run python network-api/manage.py runserver

Loading .env environment variables…
child next []
child complete
child next [ { 'http-get://localhost:8000/en': -999 } ]
child complete
child next []
child complete
Performing system checks...

System check identified no issues (0 silenced).
child next []
child complete

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): news.
Run 'python manage.py migrate' to apply them.
February 05, 2019 - 08:53:37
Django version 1.11.18, using settings 'networkapi.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2019-02-05 08:53:38,268 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,268 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,379 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,379 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,383 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,383 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,456 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,456 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,459 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,459 [INFO] "GET /en HTTP/1.1" 301 0
child next [ { 'http-get://localhost:8000/en': 200 } ]
child complete
2019-02-05 08:53:38,537 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,537 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,540 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,540 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,617 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,617 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,620 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,620 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,694 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,694 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,698 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,698 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,775 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,775 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,779 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,779 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,853 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,853 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,857 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,857 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,932 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,932 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:38,936 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:38,936 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:39,009 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,009 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,012 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:39,012 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:39,089 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,089 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,092 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:39,092 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:39,168 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,168 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,172 [INFO] "GET /en HTTP/1.1" 301 0
2019-02-05 08:53:39,172 [INFO] "GET /en HTTP/1.1" 301 0
child next []
stabilized
'cypress' is not recognized as an internal or external command,
operable program or batch file.
2019-02-05 08:53:39,252 [INFO] "GET /en/ HTTP/1.1" 200 17905
2019-02-05 08:53:39,252 [INFO] "GET /en/ HTTP/1.1" 200 17905
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! network@1.0.0 cypress:test: `wait-on -v http-get://localhost:8000/en && cypress run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the network@1.0.0 cypress:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 252, in send_preamble
    self._write(('HTTP/%s %s\r\n' % (self.http_version,self.status)).encode('iso-8859-1'))
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Program Files\Python36\Lib\socketserver.py", line 800, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-02-05 08:53:39,268 [ERROR] "GET /en/ HTTP/1.1" 500 59
npm2019-02-05 08:53:39,268 [ERROR] "GET /en/ HTTP/1.1" 500 59
 ----------------------------------------
ERR!Exception happened during processing of request from ('127.0.0.1', 51075)
 A complete log of this run can be found in:
npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2019-02-05T16_53_39_259Z-debug.log
Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 138, in run
    self.finish_response()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 332, in send_headers
    self.send_preamble()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 252, in send_preamble
    self._write(('HTTP/%s %s\r\n' % (self.http_version,self.status)).encode('iso-8859-1'))
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "C:\Program Files\Python36\Lib\socketserver.py", line 800, in write
    self._sock.sendall(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 141, in run
    self.handle_error()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\servers\basehttp.py", line 88, in handle_error
    super(ServerHandler, self).handle_error()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 368, in handle_error
    self.finish_response()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 180, in finish_response
    self.write(data)
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 274, in write
    self.send_headers()
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\Lib\socketserver.py", line 651, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Program Files\Python36\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python36\Lib\socketserver.py", line 721, in __init__
    self.handle()
  File "C:\Users\Mike\.virtualenvs\foundation.mozilla.org-4aDC7Y6j\lib\site-packages\django\core\servers\basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "C:\Program Files\Python36\Lib\wsgiref\handlers.py", line 144, in run
    self.close()
  File "C:\Program Files\Python36\Lib\wsgiref\simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
ERROR: "cypress:test" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! network@1.0.0 cypress: `run-p --race server cypress:test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the network@1.0.0 cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2019-02-05T16_53_39_397Z-debug.log
```

**Comment by jeffbski** [comment]
Please also report the output from using curl or similar tool like postman

In curl - 

curl -I -v http://localhost:8000/en

Trying to figure out why it is not seeing a 200 status code from the head response

**Comment by Pomax** [comment]
curl, then server:
```
C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org>curl -I -v http://localhost:8000/en
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to ::1 port 8000 failed: Connection refused
* connect to 127.0.0.1 port 8000 failed: Connection refused
* Failed to connect to localhost port 8000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8000: Connection refused
```

server, then curl:

```
C:\Users\Mike\Documents\Git\collaborations\mozilla\foundation.mozilla.org>curl -I -v http://localhost:8000/en
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> HEAD /en HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.55.1
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 301 Moved Permanently
HTTP/1.0 301 Moved Permanently
< Date: Tue, 05 Feb 2019 17:21:14 GMT
Date: Tue, 05 Feb 2019 17:21:14 GMT
< Server: WSGIServer/0.2 CPython/3.6.6
Server: WSGIServer/0.2 CPython/3.6.6
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Location: /en/
Location: /en/
< Content-Length: 0
Content-Length: 0
< Content-Language: en
Content-Language: en
< Referrer-Policy: same-origin
Referrer-Policy: same-origin
< X-Frame-Options: DENY
X-Frame-Options: DENY
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< Vary: Origin
Vary: Origin
< Content-Security-Policy: font-src 'self' fonts.gstatic.com fonts.googleapis.com code.cdn.mozilla.net; script-src 'self' 'unsafe-inline' cdn.optimizely.com https://www.google-analytics.com/analytics.js https://*.shpg.org/ http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js; img-src * data:; style-src 'self' 'unsafe-inline' code.cdn.mozilla.net fonts.googleapis.com; media-src 'self'; worker-src 'self'; connect-src *; child-src 'self' https://www.youtube.com/ https://s3.amazonaws.com/; default-src 'none'; form-action 'self' https://www.mozilla.org/en-US/newsletter/
Content-Security-Policy: font-src 'self' fonts.gstatic.com fonts.googleapis.com code.cdn.mozilla.net; script-src 'self' 'unsafe-inline' cdn.optimizely.com https://www.google-analytics.com/analytics.js https://*.shpg.org/ http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js; img-src * data:; style-src 'self' 'unsafe-inline' code.cdn.mozilla.net fonts.googleapis.com; media-src 'self'; worker-src 'self'; connect-src *; child-src 'self' https://www.youtube.com/ https://s3.amazonaws.com/; default-src 'none'; form-action 'self' https://www.mozilla.org/en-US/newsletter/

<

**Comment by Pomax** [comment]
note that `/en` is a 301 to `/en/`, so what should probably happen at least is accepting 2xx _and_ 3xx, because both mean the server is up, the URL is accessible, and the response is not an error (basically if it's not a 4xx or 5xx, that route is good and the details are irrelevant for waiting purposes?)

**Comment by dsdenes** [comment]
I'm facing with a pretty similar issue:

CURL:
```bash
$ curl -I -X GET http://localhost:3000/home
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Content-Type: text/html; charset=UTF-8
Content-Length: 7613
ETag: W/"1dbd-+d76Lu/gaeDRR81Xmy2xSbNeujo"
Date: Tue, 19 Feb 2019 13:43:23 GMT
Connection: keep-alive
$ curl -I -X GET http://localhost:3000/home
HTTP/1.1 200 OK
X-Powered-By: Express
Accept-Ranges: bytes
Content-Type: text/html; charset=UTF-8
Content-Length: 7613
ETag: W/"1dbd-+d76Lu/gaeDRR81Xmy2xSbNeujo"
Date: Tue, 19 Feb 2019 13:43:23 GMT
Connection: keep-alive
```
wait-on (wait-on@3.2.0)
```
$ npx wait-on -i 500 -w 500 -v http-get://localhost:3000/home
child next [ { 'http-get://localhost:3000/home': -404 } ]
child complete
child next []
child complete
child next []
child complete
.... and it goes forever
```
Do I miss something?

**Comment by afenton90** [comment]
I tried to wait on using `http` & `http-get` with the same url and it just kept going, despite the URL being accessible.
Running in verbose mode shows one `child next [ { 'http-get://localhost:4000': -400 } ]`
after that the rest are blank.

**Comment by Pomax** [comment]
@dsdenes @afenton90 can you make sure to mention which version that is for? It'll help @jeffbski a lot to know if that's thje `3.2.0` version, or whether you're seeing that on the `3.3.0-beta.0` version.

**Comment by afenton90** [comment]
@pomax it was ‘3.2.0’

**Comment by Pomax** [comment]
In that case can you please test with `3.3.0-beta.0` and report back on what that does for you, since the issue is pretty clear on the fact that 3.2.0 has this problem with a potentially fixed version that needs to be verified =)

**Comment by bibixx** [comment]
Hey @Pomax I have just tried it out as I had the same issue using Django. And running with `npx wait-on@3.3.0-beta.0 -i 500 -w 500 -v http://localhost:8000` seems to fix the issue 🎉

**Comment by arzmir** [comment]
Can confirm a related (if not exactly the same) problem on `v3.3.0` when imported as a node module. 

When reaching the timeout and `wait-on` decides to err, the polling continues. On successes it seems to correctly terminate the poller and allowing the process to terminate.

**Wait-on:** v3.3.0
**Node:** v11.12.0
**OS:** Mac OS - Mojave 10.14.6 (18G103)

**Repro:**
```javascript
const waitOn = require('wait-on');

// Will never terminate if wait-on returns the timeout-error
const expectOnline = async () => {
  try {
    await waitOn({
      resources: ['http://non-existant-server:8999/health'],
      timeout: 5000,
      log: true,
      verbose: true,
    });
    console.log('Got a response from server');
  } catch (error) {
    console.log('Server is not responding');
  }
};

expectOnline();
```

**Output:**
```javascript
child next [ { 'http://non-existant-server:8999/health': -999 } ]
wait-on(9587) waiting for: http://non-existant-server:8999/health
child complete
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
wait-on(9587) timed out waiting for: http://non-existant-server:8999/health; exiting with error
Server is not responding Error: Timeout
    at Timeout._onTimeout (..../node_modules/wait-on/lib/wait-on.js:113:10)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
child next []
child complete
(...)
```

**Comment by jeffbski** [comment]
I have a fresh rewrite of the wait-on implementation which I think is simpler and hopefully will remove some of the race conditions that were possible.

You can try out the new version 4.0.0-rc.0 by

npm i wait-on@next
Let me know if this fixes the issues you were having.

Thanks!

**Comment by jeffbski** [comment]
Released 4.0.0 which hopefully will solve these issues. Let me know if you have further problems.

https://github.com/jeffbski/wait-on/releases/tag/v4.0.0
